version: '3.4'
services:
  client:
    image: vesoft/nebula-http-client:0.0.1
    environment:
      USER: root
    ports:
      - 8080
    networks:
      - nebula-web
  web:
    image: vesoft/nebula-web-console:0.0.1
    environment:
      USER: root
      WORKING_DIR: ${WORKING_DIR}
    ports:
      - 7001
    depends_on:
      - client
    volumes:
      - ${WORKING_DIR}:${WORKING_DIR}:rw
    networks:
      - nebula-web
  importer:
    image: vesoft/nebula-importer:latest
    networks:
      - nebula-web
    ports:
      - 5699
    volumes:
      - ${WORKING_DIR}:${WORKING_DIR}:rw
    command:
      - "--port=5699"
      - "--callback=http://nginx:7001/api/import/finish"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nebula.conf
    depends_on:
      - client
      - web
      - importer
    networks:
      - nebula-web
    ports:
      - 7001:7001

networks:
  nebula-web:
