{
  "version": "v1rc1",
  "description": "web console import",
  "clientSettings": {
    "concurrency": 10,
    "channelBufferSize": 128,
    "space": "test",
    "connection": {
      "user": "user",
      "password": "password",
      "address": "192.168.3.38:3699"
    }
  },
  "logPath": "/Users/niania/WorkSpace/nebula-web-docker/example/tmp/import.log",
  "files": [
    {
      "path": "/Users/niania/WorkSpace/nebula-web-docker/example/player.csv",
      "failDataPath": "/Users/niania/WorkSpace/nebula-web-docker/example/tmp/err/Vertex 0Fail.scv",
      "batchSize": 10,
      "type": "csv",
      "csv": {
        "withHeader": false,
        "withLabel": false
      },
      "schema": {
        "type": "vertex",
        "vertex": {
          "vid": {
            "index": 0
          },
          "tags": [
            {
              "name": "person",
              "props": [
                {
                  "name": "name",
                  "type": "string",
                  "index": 1
                },
                {
                  "name": "age",
                  "type": "int",
                  "index": 2
                }
              ]
            }
          ]
        }
      }
    }
  ]
}